import React from 'react'
import { useState } from 'react';

export default function Footer() {
    const [showModal, setShowModal] = useState(false);
    const [showTerms, setShowTerms] = useState(false);
  return (
    <>
      <footer className="border-top py-4 px-4 px-md-5 d-flex flex-column flex-sm-row align-items-center gap-2 w-100">
            <p className="text-muted small mb-0">© CBC Analyzer. All rights reserved.</p>
            <nav className="ms-sm-auto d-flex gap-3">
                <button onClick = {()=> setShowTerms(true)} className="text-muted small text-decoration-none link-underline-opacity-50-hover btn btn-light">
                Terms of Service
                </button>
                <button
                    className="btn btn-light text-muted small"
                    onClick={() => setShowModal(true)}
                >
                    Privacy
                </button>
           
            </nav>
        </footer>
        {/* Modal */}
      {showModal && (
        <div
          className="modal d-block"
          tabIndex="-1"
          role="dialog"
          style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
        >
          <div className="modal-dialog" role="document">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title">Privacy Policy</h5>
                <button
                  type="button"
                  className="btn-close"
                  onClick={() => setShowModal(false)}
                  aria-label="Close"
                ></button>
              </div>
              <div className="modal-body">
                <p>Your data is processed locally and not stored.</p>
              </div>
              <div className="modal-footer">
                <button className="btn btn-dark" onClick={() => setShowModal(false)}>
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
      {showTerms && (
  <div
    className="modal d-block"
    tabIndex="-1"
    role="dialog"
    style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
  >
    <div className="modal-dialog modal-lg modal-dialog-scrollable" role="document">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Terms of Service</h5>
          <button
            type="button"
            className="btn-close"
            onClick={() => setShowTerms(false)}
            aria-label="Close"
          ></button>
        </div>
        <div className="modal-body">
          <p>
            By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Service.
          </p>

          <h6>1. Use of the Service</h6>
          <p><strong>1.1. Eligibility</strong><br />
            You must be at least 18 years of age or the age of majority in your jurisdiction to use this Service. By using the Service, you represent and warrant that you meet these requirements.
          </p>
          <p><strong>1.2. License</strong><br />
            Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, and revocable license to use the Service for personal and non-commercial purposes.
          </p>
          <p><strong>1.3. Restrictions</strong><br />
            You agree not to:
          </p>
          <ul>
            <li>Use the Service for any unlawful or prohibited purpose;</li>
            <li>Reverse engineer, decompile, or attempt to extract the source code of the Service;</li>
            <li>Transmit any viruses, malware, or other harmful code;</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          </ul>

          <h6>2. Disclaimer of Medical Advice</h6>
          <p>
            The CBC Analyzer is intended for informational and educational purposes only. It does not provide medical advice, diagnosis, or treatment. Any results, interpretations, or suggestions generated by the Service are not a substitute for professional medical judgment. Always seek the advice of a qualified healthcare provider with any questions regarding your medical condition.
          </p>

          <h6>3. Data Privacy</h6>
          <p><strong>3.1. Local Analysis</strong><br />
            We prioritize your privacy. All analysis is performed locally within your browser. No personal health information or user data is transmitted to or stored on our servers.
          </p>
          <p><strong>3.2. Third-Party Services</strong><br />
            We do not share your data with third parties. However, the Service may contain links to external sites that are not operated by us. We are not responsible for the content or privacy practices of these sites.
          </p>

          <h6>4. Intellectual Property</h6>
          <p>
            All content, features, and functionality of the Service, including but not limited to text, graphics, logos, and software, are the intellectual property of AnalyzeCBC or its licensors and are protected by applicable intellectual property laws.
          </p>

          <h6>5. Limitation of Liability</h6>
          <p>
            To the maximum extent permitted by law, in no event shall AnalyzeCBC, its affiliates, directors, officers, employees, agents, or licensors be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of or inability to use the Service.
          </p>

          <h6>6. Modifications to the Terms</h6>
          <p>
            We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting on this page. Your continued use of the Service following the posting of changes constitutes your acceptance of such changes.
          </p>

          <h6>7. Governing Law</h6>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.
          </p>
        </div>
        <div className="modal-footer">
          <button className="btn btn-dark" onClick={() => setShowTerms(false)}>
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
)}
    </>
  )
}
